### ISSUE TITLE
Saludos necesitamos conversar para proyectos

### ISSUE THREAD

**Issue by rayefv** [abr4xas/instapago#30]
Saludos excelente trabajo. Solicitamos conversar para propuesta de proyectos gracias

**Comment by abr4xas** [comment]
@rayefv hola, no había visto esto. Como me pongo en contacto?

**Comment by rayefv** [comment]
Saludos tenemos el boton de pago de banco de Venezuela/Mercantil/Petro
tienes whatsapp

**Comment by abr4xas** [comment]
@rayefv uso telegram. Me consigues con el mismo usuario (abr4xas)
